### ISSUE TITLE
Undervolt Threshold

### ISSUE THREAD

**Issue by BastelPichi** [jostsalathe/focan-uart#1]
Hey,
First of, great work. I've sniffed the communication between an g51 display and controller, and the protocol seems to be the same. Only the undervolt protection is troubling me.

I've recorded the traffic once with 36v, once with 24v. The values I'm getting are 0xD2 and 0x36.
0xD2 makes sence, 0xD2 = 210; 210 * 0.1 = 21V; 21V / 7 = 3V per cell.
However with 36V, it doesn't make any sence at all.
0x36 = 54??? Only sence here would be 0x + appending 36V???

Also, P15 is weird. All manuals say "Unspecified" and I can't set it all on my display...

Do you have any idea on this?

**Comment by BastelPichi** [comment]
For 48v, we have 0x9A = 154. Not any sence either.

**Comment by BastelPichi** [comment]
Never mind. i can set P15 - Its low voltage cuttoff, 31 for 36V Batterys.

**Comment by jostsalathe** [comment]
Hi there, thanks for the feedback!

I have an idea what may be happening on your side: I suspect you only observed the 16th byte (offset 0x0F). This is only the low byte of the `under volt threshold` value. For 24 V batteries, the 210 decivolts fit into one byte so there your reading makes sense. 310 would be 0x136 encoded in hex. You can see the 0x36 you found in your record. I suspect that the byte before that, 15th byte (offset 0x0E), contains 0x00 in your recording with P03 set to 24 V and 0x01 for the 36 V and 48 V settings. This would complete the `under volt threshold` value.

I hope this reflects your recordings and that I could help you a little with that.

**Comment by BastelPichi** [comment]
Thanks! This could be, but im not sure how this could have happened. Maybe I messed up some settings in logic 2... Imma retry with anUSB to UART, to minimize errors. However, from now this should be pretty much straight forward.

Thanks alot and merry christmas!
